services:
  soccer-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5005:5432'
    volumes:
      - soccer-db:/var/lib/postgresql/data
volumes:
  soccer-db:
    driver: local